CREATE SCHEMA todos;

CREATE SEQUENCE todos.HIBERNATE_SEQUENCE
  START WITH 1
  INCREMENT BY 1
  NO MINVALUE
  NO MAXVALUE
  CACHE 1;

CREATE TABLE todos.todos (
  id BIGINT NOT NULL,
  task VARCHAR(255),
  PRIMARY KEY (id)
);

CREATE TABLE todos.chores (
  id BIGINT NOT NULL,
  todo_id BIGINT NOT NULL,
  description VARCHAR(255),
  PRIMARY KEY (id)
);
